Scriptname CIS_RacialComments_DialogCountScript extends Quest Conditional

Int Property iDialogueCount Auto Conditional

Int Property iSubSceneDialogueCount Auto Conditional

Int Property iBrotherhoodDialogueCounter Auto Conditional